---
data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

index_count: 3000
seed_count: 100
growth_factor: 2
buffer_size: 100000
iterations: 1000000
start_time: 2016-01-01 00:00:00
time_step: 10ms
...
